# Numpy

In [1]:
import numpy as np

### EX01
Create an 3d numpy array with dimensions (4, 5, 3), and print the dimensions finally.


In [21]:
mainlist = []
count = 0
for i in range(4):
    temp =[]
    for j in range(5):
        temp.append([k for k in range(count, count+3)])
        count += 3
    mainlist.append(temp)    
        
arr453 = np.array(mainlist)
print("array(4,5,3):\n",arr453)
print("dimensions:\t",arr453.ndim)

array(4,5,3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]
dimensions:	 3


### EX02
change the shape of created array in the exercise 01 to (20, 3) and check the current dimensions!


In [24]:
arr203 = np.reshape(arr453, (20,3))
print("rashaped array:\n", arr203)

rashaped array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]
 [54 55 56]
 [57 58 59]]


### EX03
index and print the number 50 from the arr.


In [25]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr[1][0])

50


### EX04
Change the element datatype of the arr to float!


In [29]:
new_arr = arr.astype("f")

print("Previous data type:\t", arr.dtype)
print("Data type changed to:\t", new_arr.dtype)

Previous data type:	 int32
Data type changed to:	 float32


### EX05
join arr1 and arr2 into a single array!


In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr12 = np.concatenate((arr1, arr2))
arr12

array([1, 2, 3, 4, 5, 6])