# Numpy

In [1]:
import numpy as np

#### How to defining a array in numpy
Make sure that all array elements have the same data type

In [2]:
arr = np.array([1, 2,  3])

print(arr)
print("arr type: ",type(arr))

#Specifies how many dimensions our array has
print(arr.ndim)

#specifies arrays data type
print(arr.dtype)

#float array
arr_float = np.array([1, 2, 3], dtype=np.float64)
print(arr_float.dtype)

[1 2 3]
arr type:  <class 'numpy.ndarray'>
1
int32
float64


#### Another example

In [3]:
row_one = [i for i in range(10)]
row_two = [i for i in range(10, 20)]
row_three = [i for i in range(20, 30)]
row_four =  [i for i in range(30,40)]
array = np.array([row_one, row_two, row_three, row_four])

print("this array has {0} diamention!".format(array.ndim))
print("shape :", array.shape)
print("the element  data type of this array are :{0}".format(array.dtype))
print(array)

this array has 2 diamention!
shape : (4, 10)
the element  data type of this array are :int32
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


#### Another example

In [4]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print(arr.shape)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
(1, 1, 1, 1, 4)


#### Different types of arrays

In [5]:
#array 1d
print("array 1d")
print(arr)
print("")


#array 2d
print("arr_2d")
arr_2d = np.array(
    [
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]
     ])
print(arr_2d)
print("")


#array 3d
print("arr_3d")
arr_3d = np.array(
    [
     [
      [1, 2, 3],
      [4, 5, 6]
      ],
     [
      [7, 8, 9], 
      [10, 11, 12]
     ]
    ])
          
print(arr_3d)


array 1d
[[[[[1 2 3 4]]]]]

arr_2d
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr_3d
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
print("shape of array 1d:", arr.shape)
print("shape of array 2d:", arr_2d.shape)
print("shape of array 3d:", arr_3d.shape)

#(number of elements)
#(saatr, sootoun)
#(saatr, sootoun, oomgh)

shape of array 1d: (1, 1, 1, 1, 4)
shape of array 2d: (3, 3)
shape of array 3d: (2, 2, 3)


In [7]:
#zero array 2*3
arr_zero = np.zeros((2, 3), dtype=np.int32)
print("arr_zero")
print(arr_zero)

#one array
print("arr_one")

arr_one = np.ones((2, 3, 4), dtype=np.int32)
print(arr_one)


arr_zero
[[0 0 0]
 [0 0 0]]
arr_one
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [8]:
# arange(start, end, step) exactly like renge()
a = np.arange(1, 10, 2)
print(a)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [9]:
# linspace
b = np.linspace(0, 10, 3)
print(b)

[ 0.  5. 10.]


### indexing & slicing

In [10]:
#arr_1d
arr_1d = np.array([0, 1, 2, 3, 4, 5, 6])
print(arr_1d[0]) #0
print(arr_1d[4]) #4
print(arr_1d[-1]) #6


arr_1d_slicing = arr_1d[3:6]
print(arr_1d_slicing)

0
4
6
[3 4 5]


In [11]:
#indexing & slicing
#arr_2d

print(arr_2d)

print(arr_2d[1, 1])

# We separate each dimension with a comma
print(arr_2d[0:1,0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[[1 2 3]]


In [12]:
#indexing & slicing
#arr_3d

print(arr_3d)
print(arr_3d[0, 0, 1])
print(arr_3d[0:1,0:1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2
[[[1 2 3]]]


### View and Copy!

In [13]:

main_array = np.array([
    [80, 81, 82], [83, 84, 85]
    ])

copy = main_array[0:, 0:2].copy()   #copy     
view = main_array[0:, 0:2]          #view

print("main_array \n", main_array)  
print("copy \n", copy)
print("view \n", view)

main_array 
 [[80 81 82]
 [83 84 85]]
copy 
 [[80 81]
 [83 84]]
view 
 [[80 81]
 [83 84]]


### changing in copy
main array changed after changing in view.
main array didn't change after changing in copy

In [14]:
copy[0 , 0] = 0

print(">copy changed<\n", copy)
print(">main array didn't change after changing in copy< \n", main_array)

>copy changed<
 [[ 0 81]
 [83 84]]
>main array didn't change after changing in copy< 
 [[80 81 82]
 [83 84 85]]


In [15]:
#changing in view
view[0 , 0] = 0

print(">view changed< \n", view)
print(">main array changed after changing in view< \n", main_array)

>view changed< 
 [[ 0 81]
 [83 84]]
>main array changed after changing in view< 
 [[ 0 81 82]
 [83 84 85]]


### sum of arrays element peer to peer

In [16]:
arr0 = np.array([
    [1, 2], [5, 6]
    ])

arr1 = np.array([
    [5, 10], [25, 30]
    ])

suming = np.add(arr0, arr1)
subtracting = np.subtract(arr0, arr1)
multiplying = np.multiply(arr0, arr1)
dividing = np.divide(arr0, arr1)

print("sum of arraies element:\n", suming)
print("\nsubtract of arraies element:\n", subtracting)
print("\nmultiply of arraies element:\n", multiplying)
print("\ndivide of arraies element:\n", dividing)

sum of arraies element:
 [[ 6 12]
 [30 36]]

subtract of arraies element:
 [[ -4  -8]
 [-20 -24]]

multiply of arraies element:
 [[  5  20]
 [125 180]]

divide of arraies element:
 [[0.2 0.2]
 [0.2 0.2]]


### mean

In [17]:
print("array :\n", main_array)
print("mean of main array is ", np.mean(main_array))

array :
 [[ 0 81 82]
 [83 84 85]]
mean of main array is  69.16666666666667


### sum of elements of array

In [18]:
np.sum(main_array)

415

### Standard Deviation

In [19]:
# new array
arr2 = np.array([100, 154, 81, 94, 32])

np.std(arr2)

39.07121702737195

### Variance

In [20]:
np.var(arr2)

1526.56

### minimum

In [21]:
np.amin(arr2)

32

### maximum

In [22]:
np.amax(arr2)

154

### sorting array

In [23]:
np.sort(arr2)

array([ 32,  81,  94, 100, 154])

### reshaping

In [24]:
#reshape
arr3 = np.arange(1, 5)
arr4 = np.reshape(arr3, (2, 2))
arr5 = np.reshape(arr3, (4, 1))

print("array\n", arr3)
print("\n reshaped array\n", arr4)
print("\n reshaped array\n", arr5)

array
 [1 2 3 4]

 reshaped array
 [[1 2]
 [3 4]]

 reshaped array
 [[1]
 [2]
 [3]
 [4]]
